modLoader="javafml"
loaderVersion="[31,)" 
[[mods]] #mandatory
modId="pickled_vegetable"
version="None"
displayName="pickled_vegetable"
authors="bili_08A04_NQ3"
description='老 坛 酸 菜'
displayURL = "https://space.bilibili.com/538864655"